name: Generate Snake Animation

on:
  schedule: 
    - cron: "0 */1 * * *"  
  workflow_dispatch: 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Cloning the Repository
        uses: actions/checkout@v2

      - name: Generate Snake
        uses: Platane/snk@v2
        with:
          github_user_name: martinssluis
          outputs: dist/snake.svg

      - name: Upload Snake Animation
        uses: actions/upload-artifact@v2
        with:
          name: snake-animation
          path: dist/snake.svg

      - name: Commit and Push Snake Animation
        run: |
          git config --local user.name "GitHub Actions"
          git config --local user.email "actions@github.com"
          git add -A
          git commit -m "Generated snake animation"
          git push
